name: build

on:
  create:
    tags:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: publish
      run: ./gradlew --warning-mode all build

